#ifndef DM_APP_DEFINES_H
#define DM_APP_DEFINES_H

#define DM_MAX_THREAD_COUNT 24

#define DM_ECS_MAX_ENTITIES 4096

#define DM_PHYSICS_BAUMGARTE_COEF 0.01f
#define DM_PHYSICS_BAUMGARTE_SLOP 0.005f

#define DM_PHYSICS_REST_COEF 0.1f
#define DM_PHYSICS_REST_SLOP 0.5f

#endif //DM_APP_DEFINES_H
