#ifndef DM_APP_DEFINES_H
#define DM_APP_DEFINES_H

#define DM_MAX_THREAD_COUNT 32

#define DM_ECS_MAX_ENTITIES 2048

#define DM_PHYSICS_BAUMGARTE_COEF 0.15f
#define DM_PHYSICS_BAUMGARTE_SLOP 0.001f

#define DM_PHYSICS_REST_COEF 0.1f
#define DM_PHYSICS_REST_SLOP 0.1f

#endif //DM_APP_DEFINES_H
